"""initial

Revision ID: 7f6150724846
Revises: 
Create Date: 2025-07-12 22:58:45.323277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6150724846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_permission',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('auth_user',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('login')
    )
    op.create_table(
        "auth_user_permission",
        sa.Column("user_uuid", sa.UUID(), sa.ForeignKey("auth_user.uuid"), primary_key=True),
        sa.Column("permission_name", sa.String, sa.ForeignKey("global_permission.name"), primary_key=True),
    )
    op.create_table(
        "auth_session",
        sa.Column("session_token", sa.String, primary_key=True),
        sa.Column("user_uuid", sa.UUID(), sa.ForeignKey("auth_user.uuid", ondelete="CASCADE"), nullable=False),
        sa.Column("last_login", sa.DateTime, nullable=False),
        sa.UniqueConstraint("user_uuid"),
    )


def downgrade() -> None:
    op.drop_table('auth_user')
    op.drop_table('global_permission')
    op.drop_table('auth_user_permission')
    op.drop_table('auth_session')
